import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';

import './globals.css';
import { cn } from '../shared/lib/utils';
import AppHeader from '../widgets/app-header/AppHeader';
import Providers from './_providers/Providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(fontSans.variable)}>
        <Providers>
          <AppHeader />
          {children}
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
